// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgBot.Models;

#nullable disable

namespace TgBot.Migrations
{
    [DbContext(typeof(DriverContext))]
    [Migration("20211130090352_test7")]
    partial class test7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TgBot.Models.CurRoute", b =>
                {
                    b.Property<long>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordID"), 1L, 1);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverForeignKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsFromFirstStop")
                        .HasColumnType("bit");

                    b.Property<string>("NumberOfIncoming")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NumberOfLeaving")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RouteForeignKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeOfStops")
                        .HasColumnType("varchar(max)");

                    b.HasKey("RecordID");

                    b.HasIndex("DriverForeignKey");

                    b.HasIndex("RouteForeignKey");

                    b.ToTable("MyCurRoutes");
                });

            modelBuilder.Entity("TgBot.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrdinalRouteRouteId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DriverId");

                    b.HasIndex("OrdinalRouteRouteId");

                    b.ToTable("MyDrivers");
                });

            modelBuilder.Entity("TgBot.Models.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("NumberOfStops")
                        .HasColumnType("tinyint");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("MyRoutes");
                });

            modelBuilder.Entity("TgBot.Models.CurRoute", b =>
                {
                    b.HasOne("TgBot.Models.Driver", "Driver")
                        .WithMany("HistoryRoutes")
                        .HasForeignKey("DriverForeignKey");

                    b.HasOne("TgBot.Models.Route", "Route")
                        .WithMany("RoutesHistory")
                        .HasForeignKey("RouteForeignKey");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TgBot.Models.Driver", b =>
                {
                    b.HasOne("TgBot.Models.Route", "OrdinalRoute")
                        .WithMany()
                        .HasForeignKey("OrdinalRouteRouteId");

                    b.Navigation("OrdinalRoute");
                });

            modelBuilder.Entity("TgBot.Models.Driver", b =>
                {
                    b.Navigation("HistoryRoutes");
                });

            modelBuilder.Entity("TgBot.Models.Route", b =>
                {
                    b.Navigation("RoutesHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
