// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgBot.Models;

#nullable disable

namespace TgBot.Migrations
{
    [DbContext(typeof(TgBotContext))]
    partial class DriverContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TgBot.Models.CurRoute", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordId"), 1L, 1);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumberOfIncoming")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NumberOfLeaving")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeOfStops")
                        .HasColumnType("varchar(max)");

                    b.HasKey("RecordId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("MyCurRoutes");
                });

            modelBuilder.Entity("TgBot.Models.Driver", b =>
                {
                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("DriverId");

                    b.ToTable("MyDrivers");
                });

            modelBuilder.Entity("TgBot.Models.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Stops")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.ToTable("MyRoutes");
                });

            modelBuilder.Entity("TgBot.Models.CurRoute", b =>
                {
                    b.HasOne("TgBot.Models.Driver", "Driver")
                        .WithMany("RoutesList")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgBot.Models.Route", "Route")
                        .WithMany("RoutesHistory")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TgBot.Models.Driver", b =>
                {
                    b.Navigation("RoutesList");
                });

            modelBuilder.Entity("TgBot.Models.Route", b =>
                {
                    b.Navigation("RoutesHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
